#!/bin/sh

#######################################################################
# This pre-commit hooks checks for changed or new JavaScript files
# in the commit and tries to validated them with jshint.
# If any staged file doesn't validate, you don't get to commit the file.
#
# Only three things are required for this script:
# - JSHint must be installed as a commandline tool.
# - the file jshint.conf must exist at the base of the git repository,
#    it contains a JSON with the config parameters for node.js scripts.
# - the file jshint_browser.conf must also exist, this is the same as 
#    the jshint.conf just for the browser. It'll be used on files in
#    the path "public/javascripts", all other files will be validated
#    with the jshint.conf.
#
#######################################################################

has_error=0

which jshint > /dev/null
if [ $? -gt 0 ]; then
	echo "You need JSHint for this, install via 'npm install -g jshint'";
	exit 1;
fi

if [ ! -f "jshint.conf" ]; then
	echo "No jshint.conf exists"
	exit 1;
fi

if [ ! -f "jshint_browser.conf" ]; then
	echo "No jshint_browser.conf exists"
	exit 1;
fi

# GIT_WORKING_DIR apparently it's $PWD, cache this path
WORKING_DIR=$PWD

# Generate a tmp-dir-base-that doesn't overlap with others
TMP_BASEDIR=/dev/shm/git_hook_$( date | sha1sum | cut -d" " -f1 );
# echo $WORKING_DIR;
# echo $TMP_BASEDIR;
for file in $(git diff-index --name-only --cached HEAD --diff-filter=AMCT); do
	# echo $file

	echo $file | grep "\.js\$" > /dev/null
	if [ $? -eq 0 ]; then
		# Get the staged files hash
		show=$(git diff-index --cached HEAD --diff-filter=AMCT "$file" | cut -d" " -f4);

		# Make the tmp-path for the file
		TMP_WORKFILE="${TMP_BASEDIR}/${file}";

		# Create the directory for the TMP_WORKFILE
		mkdir -p "$( dirname $TMP_WORKFILE )";

		# Oh, what config file to use? The one for the files for node.js or the one for files for the browser
		config_file="jshint.conf"
		echo $file | grep "public\/javascripts\/" > /dev/null;
		if [ $? -eq 0 ]; then
			config_file="jshint_browser.conf"
		fi

		# Get the staged file from the index and put it in our working dir, keep the path so it's easier to read.
		git show "$show" > "$TMP_WORKFILE";

		# Go to the tmpbase dir
		cd "$TMP_BASEDIR";

		# Run jshint on the files
		jshint --config "${WORKING_DIR}/${config_file}" "$file"
		if [ $? -gt 0 ]; then
			has_error=1;
			echo "$file failed to validate in JSHint using ${config_file}"
		else
			echo "$file validated with JSHint using ${config_file}"
		fi

		# Remove the tmp file and the directory we made for it.
		rm "$TMP_WORKFILE"
		rmdir "$( dirname $TMP_WORKFILE )";

		# Return to the working dir
		cd $WORKING_DIR
	fi
done;

rm -rf "$TMP_WORKFILE";

exit $has_error
